# Generated by Django 3.1.5 on 2021-03-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210319_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.BigIntegerField(),
        ),
    ]
